[package]
name = "descent"
authors = ["John M Archer <archer884@zoho.com"]
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.22", features = ["derive", "wrap_help"] }
